Add senders to block result
covalenthq/erigon pull request #10
Opened 2022-07-21 20:37 UTC by fatemebagherii

2022-07-27 02:28 UTC, sudeepdino008 requested changes

2022-07-27 02:28 UTC, sudeepdino008 commented on core/blockchain.go
> +			signer := types.MakeSigner(chainConfig, block.NumberU64())
1. let's move this to outside ExecuteBlockEphemerally and into transition.go
2. you can use tx.Sender(Signer) for this, it caches the sender and returns it in case "from" field is already populated.
3. avoid created a signer for each transaction, check if can reuse the signer across transactions

2022-07-27 20:44 UTC, fatemebagherii commented on core/blockchain.go
> +			signer := types.MakeSigner(chainConfig, block.NumberU64())
aren't we already using `tx.Sender(Signer)`?
yeah, it uses the "from" field in `CommonTx.TransactionMisc`, but I need to feed it a signer and from what I see, I can either use `types.LatestSignerForChainID()` or `types.MakeSigner()` to get a signer. Isn't that right?

2022-07-28 08:14 UTC, sudeepdino008 commented on core/blockchain.go
> +			signer := types.MakeSigner(chainConfig, block.NumberU64())
ah, i see it's already using tx.Sender(signer). Cool.
I got some new inputs from Levi around Senders. According to him, "sender recovery" is expensive (sometimes more expensive that rest of the block execution). I've tagged you in the thread in slack. Waiting for his inputs to decide what exactly to do here. You can pause this for now.

2022-08-02 22:12 UTC, fatemebagherii commented on core/blockchain.go
> +			signer := types.MakeSigner(chainConfig, block.NumberU64())
I made some changes regarding sender's recovery. How do they look?

2022-08-09 04:51 UTC, sudeepdino008 approved these changes

2022-08-09 04:52 UTC, merged