Erigon 2.40.0
covalenthq/erigon pull request #16
Opened 2023-03-07 14:39 UTC by sudeepdino008

2023-03-07 18:40 UTC, rogarcia requested changes
seems there quite a few dependency problems and doesn't compile

2023-03-07 18:40 UTC, rogarcia commented on core/types/legacy_tx.go
>  func (ct *CommonTx) SetFrom(from common.Address) {
need to update this func too with *libcommon.Address right?

2023-03-07 18:40 UTC, rogarcia commented on turbo/stages/headerdownload/header_algos.go
>  			return false, true, 0, nil
../../turbo/stages/headerdownload/header_algos.go:526:27: not enough return values
	have (bool, bool, number, nil)
	want (bool, bool, uint64, uint64, error)

2023-03-07 18:40 UTC, rogarcia commented on turbo/stages/headerdownload/header_algos.go
>  		}
../../turbo/stages/headerdownload/header_algos.go:546:28: not enough return values
	have (bool, bool, number, nil)
	want (bool, bool, uint64, uint64, error)

2023-03-07 18:40 UTC, rogarcia commented on core/vm/interpreter.go
> +	libcommon "github.com/ledgerwatch/erigon-lib/common"
../../core/vm/interpreter.go:82:19: undefined: common
../../core/vm/interpreter.go:83:19: undefined: common
../../core/vm/interpreter.go:84:19: undefined: common

2023-03-08 12:39 UTC, sudeepdino008 commented
@tsutsu the evm tool tests work. Not sure how to test eth_multicall. Do you have pointers?

2023-03-21 16:13 UTC, noslav commented
> 
@sudeepdino008 
I've some tooling/sources to make calls to multicall but on the client side, so that node PR has to be deployed to be tested against.

2023-03-31 08:43 UTC, closed without merging